### PR TITLE
Update to fix 'object is not a function' async race

### PR DESCRIPTION
**Pull request by mikeangstadt**
Updated to ensure callback is a function before it is called.

### CODE REVIEW

**Comment by jorgebay** [comment]
Do you have a way to reproduce it?

We have been hitting this issue on our integration servers from time to time while running [this test that is designed to try to create race conditions](https://github.com/datastax/nodejs-driver/blob/3748dc1b5b40012a1ce91e4bf72c0cc95d2a180f/test/integration/short/client-execute-prepared-tests.js#L58), but we can not accurately find the underlying cause...

**Comment by mikeangstadt** [comment]
It occurs when you load test reads across multiple keyspaces - due to the round robin rotation through connections hitting multiple keyspaces.  If the code cycles quickly enough you'll round-trip since the .next connection is used if the keyspace is different then the last connections.

eg, fill a keyspace 'foo' and column family 'blips' with 10,000 trivial records
fill a keyspace 'fum' and column family 'bars' with 10,000 trivial records which contain references to records in 'foo'

setup an async parallel call to get a list of 1,000 bars by id from fum and hydrate their blips from foo.

* note: you'll eventually get this error.

**Comment by jorgebay** [comment]
Ok, thanks for the tip, we will try that.

As a note, you should use 2 different client instances in those situations, one per keyspace.
Either that or you should "fully qualify" your table names, ie: `SELECT x, w, z FROM ks1.tbl1`.

**Comment by mikeangstadt** [comment]
Thanks for the tip, hopefully since this is merely a defensive check to alleviate the issue it'll be an easy call to merge - cheers!

**Comment by mikeangstadt** [comment]
ping on this @jorgebay - mind addressing this as it's a non-breaking defensive check?

**Comment by jorgebay** [comment]
We are still trying to determine the underlying cause, we don't want to risk a response not being called back. I will let u know as soon as we have something.

**Comment by mikeangstadt** [comment]
Understood but the only risk to a response not being called back is if the
callback isn't an executable function - which would fail regardless.

On Fri, May 22, 2015 at 2:54 AM, Jorge Bay Gondra <notifications@github.com>
wrote:

> We are still trying to determine the underlying cause, we don't want to
> risk a response not being called back. I will let u know as soon as we have
> something.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/datastax/nodejs-driver/pull/47#issuecomment-104556245>
> .
>



-- 
Mike Angstadt
www.mikeangstadt.com
@mike_angstadt <http://www.twitter.com/mike_angstadt> | LinkedIn
<http://www.linkedin.com/in/mikeangstadt>
610-914-4409

*"The noblest pleasure is the joy of understanding" - Leonardo Di Vinci*

**Comment by jorgebay** [comment]
We merged #55 that fixes this issue. Even though your pull request did solved the bug, we decided to find the root cause and fix that.

**Pull request closed without merging**
