### PR TITLE
Bugfix/nodejs 633 cannot read property executor

### PR DESCRIPTION
**Pull request by matchish**
Fix https://datastax-oss.atlassian.net/browse/NODEJS-633

### CODE REVIEW

**Comment by absurdfarce** [comment]
@matchish Thanks for the submission!  This looks pretty good to me so I think we can move forward with it.

Have you signed the Contributor License Agreement for contributions to DataStax open source projects? If not you can find it at https://cla.datastax.com/. Thanks!

**Comment by matchish** [comment]
@absurdfarce Yes I've signed the agreement

**Comment by absurdfarce** [comment]
Excellent, thank you!  And thanks again for the contribution!

**Review by absurdfarce — APPROVED** [review]

**Comment by michaelwittwer** [comment]
@absurdfarce thanks for merging this. Do you have a Date when the `4.6.4` release will be done, including this fix?

**Comment by absurdfarce** [comment]
@michaelwittwer I don't have a target date for the next nodejs release at the moment.  I'd like to get one, perhaps two other tickets in before putting out a full release.  Is there a specific time frame you're working towards?

**Comment by absurdfarce** [comment]
@michaelwittwer The fix implemented in this PR has been included in version 4.6.4 of the nodejs driver.  That version was just released today.

**Comment by michaelwittwer** [comment]
@absurdfarce thanks for the update - this is great news.

**Pull request merged**
