### PR TITLE
fix unsigned integer bits operation in toBuffer

### PR DESCRIPTION
**Pull request by Arhey**

### CODE REVIEW

**Comment by Arhey** [comment]
jorgebay, Try this example^

var Cassandra = require('cassandra-driver');
var fromString = Cassandra.types.Integer.fromString('b70cefb9c19c9c5112972fd01a4e676d', 16);
var convert = Cassandra.types.Integer.fromBuffer(Cassandra.types.Integer.toBuffer(fromString));

console.log('From string: ', fromString);
console.log('Convert: ', convert);

**Comment by Arhey** [comment]
version fixes bugs: highBits >>> 24 > 0 or highBits >> 24 != 0

**Comment by jorgebay** [comment]
Thanks the explanation @Arhey !

It was hard for me to understand because all the tests start with the Cassandra representation, so going back and forward (fromBuffer and toBuffer) was not a problem.

If a positive number with the most significant bit 'on' is originally represented in the driver, it can result in a error.

I will create a ticket and merge your commit.

**Comment by jorgebay** [comment]
I merged it and added covering test cases 3ee43fb0968b685fef89b57a0b7456fb6587ebea.

**Comment by Arhey** [comment]
Excellent!

**Pull request merged**
