### PR TITLE
NODEJS-375 Allow async creation of Uuid

### PR DESCRIPTION
**Pull request by guzmo**
I was supposed to create a small benchmark of async vs sync but I've had no time :( I ran some small tests with https://www.npmjs.com/package/loadtest, but only on my computer, which are running a lot of other processes at the same time, so hard to tell. 
Hope the code is not too messy ;)

### CODE REVIEW

**Comment by guzmo** [comment]
The Synchronous function might be faster for creating a small amount of bytes ( which Uuid is doing I think ), but it might be safer to use the async because you might block the node process.
https://github.com/nodejs/help/issues/457

Well, your choice if you want to have it.

**Comment by jorgebay** [comment]
As [discussed in the ticket](https://datastax-oss.atlassian.net/browse/NODEJS-375), I think is a good idea to have an asynchronous overload of `Uuid.random()`.

About `TimeUuid`, do you want to add support for callbacks for `TimeUuid.now()` and `TimeUuid.fromDate()` in this patch? Otherwise, we can create a separate ticket for it.

**Comment by guzmo** [comment]
@jorgebay Can we create separate tickets for TimeUuid? :) One step at a time is usually a good thing and would be nice to at least get this fix in an upcoming release.
Does it look good otherwise? Some tests timed out, maybe I should look at them?

Cheers

**Comment by jorgebay** [comment]
ok, I've created a separate ticket for `TimeUuid`: [NODEJS-387](https://datastax-oss.atlassian.net/browse/NODEJS-387).

I'll talk with the rest of the team to see if we can include it for the upcoming v3.3.0 today and let you know.
The patch is looking good, I'll do a full review soon.

**Comment by jorgebay** [comment]
We will try to include it for v3.3.0 release.

**Comment by guzmo** [comment]
Good catches! Will fix the review comments tonight.

**Comment by jorgebay** [comment]
Landed in cb89374.
Thanks @guzmo !

**Comment by guzmo** [comment]
No problem, glad to help :)

**Pull request merged**
