### PR TITLE
TokenAware lb policy test fixes

### PR DESCRIPTION
**Pull request by tolbertam**
Please hold off on merging for now, will have another fix that addresses a rare issue with traces.

### CODE REVIEW

**Comment by tolbertam** [comment]
Removing wip tag, can't get the tracing issues to occur in openstack environment.  This fix is needed for DSE compatibility so i think it can be merged as is while i continue to wrap my head around the tracing issues.

**Comment by tolbertam** [comment]
Ok so i was able to reproduce the other issue i was digging into in an openstack environment.  I think it may be related to the replica selection being random in token aware policy.   With 10 attempts, the possibility of the same replica (of 2 replicas) being chosen each time is 1/1024 ((1/2)^10) which is pretty low.  

But there are 10 series of 10 attempts in a test (5/512), and then 2 varieties of this test (5/256), and we have a nightly matrix of 24 configurations , which reduces the probability of this occurring in our nightly matrix to 15/32 or roughly 1/2 which seems about right.

I think to make the test more reliable we need to increase the number of queries executed per iteration.  Setting it to 100 will make the test take longer (not really noticeable), but also more reliable as the starting basis probability will be 1/2^100 which is a very low probability.

**Comment by tolbertam** [comment]
Github must be having problems because my commit isn't showing up on the PR, but once that shows up this should be good to go

**Comment by tolbertam** [comment]
closed/reopened and now the commit shows up.

**Comment by jorgebay** [comment]
> But there are 10 series of 10 attempts in a test (5/512), and then 2 varieties of this test (5/256), and we have a nightly matrix of 24 configurations , which reduces the probability of this occurring in our nightly matrix to 15/32 or roughly 1/2 which seems about right.

Great development of something that is not evident at first. Its funny how choosing an "intermediate" number of attempts made it worst: the failure didn't appear on most "commit" builds but was still very likely to appear on nightly builds. For example, if I used `20` instead of `10` initially would have make it very unlikely on nightly as well.

**Pull request merged**
