### PR TITLE
Drop support for Node.js 0.10 / 0.12 and domains

### PR DESCRIPTION
**Pull request by jorgebay**

### CODE REVIEW

**Comment by jorgebay** [comment]
I don't know why job creator skipped it...

**Comment by tolbertam** [comment]
> I don't know why job creator skipped it...

I'll look into it, it looks like the updater is running, but maybe having issues for some reason, will figure it out.

**Comment by tolbertam** [comment]
>   failure - Unhandled exception (RuntimeError: not supported version "8" for "nodejs")  

That's the issue there,  I'll add the version to the runtimes for nodejs

**Comment by tolbertam** [comment]
Apologies for the branch delete/recreate spam, jenkins issue should be fixed now.

**Comment by tolbertam** [comment]
Some very odd behavior for nodejs 8 only in the jenkins environment...:

```
7:16:04 npm notice created a lockfile as package-lock.json. You should commit this file.
17:16:04 added 2 packages in 1.131s
17:16:10 Current cluster is now: test_samples
17:16:10 fs.js:948
17:16:10   binding.stat(pathModule._makeLong(path));
17:16:10           ^
17:16:10 
17:16:10 Error: ELOOP: too many symbolic links encountered, stat '/home/jenkins/workspace/datastax.nodejs-driver.NODEJS-363.commit/0ec4703d/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver/examples/node_modules/cassandra-driver'
17:16:10     at Object.fs.statSync (fs.js:948:11)
17:16:10     at /home/jenkins/workspace/datastax.nodejs-driver.NODEJS-363.commit/0ec4703d/examples/runner.js:18:12
17:16:10     at Array.forEach (<anonymous>)
17:16:10     at getJsFiles (/home/jenkins/workspace/datastax.nodejs-driver.NODEJS-363.commit/0ec4703d/examples/runner.js:17:9)
17:16:10     at /home/jenkins/workspace/datastax.nodejs-driver.NODEJS-363.commit/0ec4703d/examples/runner.js:19:7
17:16:10     at Array.forEach (<anonymous>)
17:16:10     at getJsFiles (/home/jenkins/workspace/datastax.nodejs-driver.NODEJS-363.commit/0ec4703d/examples/runner.js:17:9)
17:16:10     at /home/jenkins/workspace/datastax.nodejs-driver.NODEJS-363.commit/0ec4703d/examples/runner.js:19:7
17:16:10     at Array.forEach (<anonymous>)
17:16:10     at getJsFiles (/home/jenkins/workspace/datastax.nodejs-driver.NODEJS-363.commit/0ec4703d/examples/runner.js:17:9)
```

Looking into it, maybe something messed up with the nodejs install or something we need to adjust.  Will figure it out

**Comment by tolbertam** [comment]
Looks like an issue with npm 5 and symbolic links, issue here looks similar: https://github.com/katzer/cordova-plugin-local-notifications/issues/1329.   Will find a resolution

**Comment by tolbertam** [comment]
Ah, actually it's not related at all, the problem is `getJsFIles` is entering the node_modules directory which ends up following symbolic links repeatedly as examples/node_modules/cassandra-driver symlinks to ../, which contains the examples directly and it repeats indefinitely.  We can just suppress node_modules to fix this.

**Comment by tolbertam** [comment]
It looks like older versions of npm just copied the directory where newer versions symlink, that's the difference.  In any case, i'll push a fix shortly!

**Comment by jorgebay** [comment]
Thanks for the fix!

**Pull request merged**
