### PR TITLE
Use class syntax and use arrow functions

### PR DESCRIPTION
**Pull request by jorgebay**
[As detailed in the ticket](https://datastax-oss.atlassian.net/browse/NODEJS-406) there is a feature on ES6 that prevents us from moving public declarations to class syntax (`TypeError: Class constructor cannot be invoked without 'new'`).

I've migrated some of the internal prototypes and included the eslint rule `constructor-super` which is super useful in implementations like `Request`.
I've also changed some occurrences of functions to arrow functions and, as explained in the ticket comments, I've included the rule `"arrow-body-style": ["error", "as-needed"]`.

I'm happy with the result, specially with modules like `requests.js`, `prepare-handler.js`, `operation-state.js`. If I have more time, I would like to migrate `stream-id-stack.js`, `tokenizer.js` and `writers.js`.

### CODE REVIEW

**Comment by jorgebay** [comment]
Good input @landim, I've changed the suggested fn declarations into arrows.

I've also used class syntax for writers, tokenizers and `StreamIdStack`.

**Comment by jorgebay** [comment]
As this is a large change set, I'm pinging @landim and @tolbertam for reviewing to avoid conflicts with other dev branches.

**Comment by tolbertam** [comment]
> As this is a large change set, I'm pinging @landim and @tolbertam for reviewing to avoid conflicts with other dev branches.

:+1: i'll take a look at it this morning.  I think it would be pretty easy to rebase my PR after this is merged as the changes are pretty localized there, so I'm ok with this one being merged first.

**Comment by jorgebay** [comment]
ok, I'll take the opportunity and merge it, thanks!

**Pull request merged**
