### PR TITLE
Allow socket close event to be emitted before connection close calls back

### PR DESCRIPTION
**Pull request by jorgebay**
https://datastax-oss.atlassian.net/browse/NODEJS-165

### CODE REVIEW

**Comment by tolbertam** [comment]
Looks good to me, reproduced issue on windows with 2.1.9 against master and can't reproduce problem on this branch :+1:

**Comment by deepakkb** [comment]
Hello Jorge,
I installed nodejs cassandra driver 2.2.2 and having this issue. Do you have any suggestions?.

**Comment by jorgebay** [comment]
Could you post the error and stack trace @deepakkb ?

**Comment by deepakkb** [comment]
When my NODEJS code in Windows calls cassandra server with a simple CSQL like "select * from table1" , following is the response I get

"Error: No host could be resolved,info=Represents an error when a query cannot be performed because no host is available or could be reached by the driver.,innerErrors=null".

However I can do telnet to the Cassandra server using the IP address default port 9042 and can do ping the server. So there is no connectivity issue between my machine and the Cassandra server. This is an existing server which the .NET program can communicate successfully but NODEJS cannot. Yesterday after reading the post at https://datastax-oss.atlassian.net/browse/NODEJS-165, I downloaded Cassandra driver 2.2.2 but no luck. Should I install a older version?

**Comment by jorgebay** [comment]
Which are the parameters you are using to create the `Client` instance?
Can you post the [driver logs](https://github.com/datastax/nodejs-driver#logging)?

Using v2.2.2 of the driver is OK.

**Pull request merged**
