### PR TITLE
fixes broken link for 'Connection pooling'

### PR DESCRIPTION
**Pull request by theRemix**

### CODE REVIEW

**Comment by jorgebay** [comment]
I can merge it as soon as you sign the contributor agreement, there is a FAQ section that answers most of the common doubts about these types of agreements.

**Comment by theRemix** [comment]
signed

**Comment by avalanche123** [comment]
@theRemix you haven't signed it yet. You've completed the form and we've sent the document to your email, check your inbox. I can resend if you can't find it.

**Comment by jorgebay** [comment]
Rebased and merged 9aae1dd552cd2f5b430b8ce72fbb15895ce483aa.
Thanks @theRemix !

**Pull request closed without merging**
