### PR TITLE
Resolve domains without dots

### PR DESCRIPTION
**Pull request by jorgebay**
Includes changes in #213 by @guyellis and patch from @tolbertam

### CODE REVIEW

**Comment by jorgebay** [comment]
I've made a minor change in the test, to use `Array.prototype.filter` instead of `find` as it's not available in node <= 0.12.

The new approach looks good to me.

**Comment by tolbertam** [comment]
> I've made a minor change in the test, to use Array.prototype.filter instead of find as it's not available in node <= 0.12.

D'oh!  Good catch 👍

**Comment by jorgebay** [comment]
Merged, thanks @guyellis !

**Comment by guyellis** [comment]
@tolbertam @jorgebay when will this get published to Npm?

**Comment by jorgebay** [comment]
We don't have a target date yet but you can follow the progress of v3.2.2 release on JIRA: https://datastax-oss.atlassian.net/browse/NODEJS-358?filter=-4&jql=project%20%3D%20NODEJS%20AND%20fixVersion%20in%20(3.2.2)%20ORDER%20BY%20updated%20

**Pull request merged**
