### PR TITLE
Encoding Date as BigInt if useBigIntAsLong is true

### PR DESCRIPTION
**Pull request by dreaf**
See https://datastax-oss.atlassian.net/browse/NODEJS-586

### CODE REVIEW

**Comment by jorgebay** [comment]
Thanks for creating the ticket and the pull request. The steps for reproducing it are straightforward, nice!

I'll add an integration test for it today/tomorrow and merge it.

**Comment by jorgebay** [comment]
Landed in edd4230dc6d27245d74f09e4f539b48c67645c39 and included test in 73b04c8923c86ddb0d19da24f40e7fb582a1e36e.

**Comment by jorgebay** [comment]
Thanks @dreaf !!

**Comment by dreaf** [comment]
Thanks for reacting that fast! 😄

**Pull request merged**
